config/routes.rb
Vidashop::Application.routes.draw do
  resources :acessos

  resources :clicks

  devise_for :users
  resources :servers do
    get 'grafico', :on => :collection
    get 'deletar_emails', :on => :collection
    get 'limpar_db', :on => :collection
  end

  resources :emails do
    get 'top', :on => :collection
    get 'exportar_top', :on => :collection
    get 'exportar_acessos', :on => :collection
  end

  root 'servers#index'

  

end

app/models/acesso.rb
class Acesso < ActiveRecord::Base
  belongs_to :email
end

app/controllers/acessos_controller.rb
class AcessosController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_acesso, only: [:show, :edit, :update, :destroy]

  # GET /acessos
  # GET /acessos.json
  def index
    @acessos = Acesso.all
  end

  # GET /acessos/1
  # GET /acessos/1.json
  def show
  end

  # GET /acessos/new
  def new
    @acesso = Acesso.new
  end

  # GET /acessos/1/edit
  def edit
  end

  # POST /acessos
  # POST /acessos.json
  def create
    @acesso = Acesso.new(acesso_params)

    respond_to do |format|
      if @acesso.save
        format.html { redirect_to @acesso, notice: 'Acesso was successfully created.' }
        format.json { render action: 'show', status: :created, location: @acesso }
      else
        format.html { render action: 'new' }
        format.json { render json: @acesso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acessos/1
  # PATCH/PUT /acessos/1.json
  def update
    respond_to do |format|
      if @acesso.update(acesso_params)
        format.html { redirect_to @acesso, notice: 'Acesso was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @acesso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acessos/1
  # DELETE /acessos/1.json
  def destroy
    @acesso.destroy
    respond_to do |format|
      format.html { redirect_to acessos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_acesso
      @acesso = Acesso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def acesso_params
      params.require(:acesso).permit(:server_id, :email_id, :data)
    end
end

app/helpers/acessos_helper.rb
module AcessosHelper
end

app/views/acessos/_form.html.erb
<%= form_for(@acesso) do |f| %>
  <% if @acesso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@acesso.errors.count, "error") %> prohibited this acesso from being saved:</h2>

      <ul>
      <% @acesso.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :server_id %><br>
    <%= f.number_field :server_id %>
  </div>
  <div class="field">
    <%= f.label :email_id %><br>
    <%= f.number_field :email_id %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.date_select :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/acessos/edit.html.erb
<h1>Editing acesso</h1>

<%= render 'form' %>

<%= link_to 'Show', @acesso %> |
<%= link_to 'Back', acessos_path %>

app/views/acessos/index.html.erb
<h1>Listing acessos</h1>

<table>
  <thead>
    <tr>
      <th>Server</th>
      <th>Email</th>
      <th>Data</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @acessos.each do |acesso| %>
      <tr>
        <td><%= acesso.server_id %></td>
        <td><%= acesso.email_id %></td>
        <td><%= acesso.data %></td>
        <td><%= link_to 'Show', acesso %></td>
        <td><%= link_to 'Edit', edit_acesso_path(acesso) %></td>
        <td><%= link_to 'Destroy', acesso, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Acesso', new_acesso_path %>

app/views/acessos/new.html.erb
<h1>New acesso</h1>

<%= render 'form' %>

<%= link_to 'Back', acessos_path %>

app/views/acessos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Server:</strong>
  <%= @acesso.server_id %>
</p>

<p>
  <strong>Email:</strong>
  <%= @acesso.email_id %>
</p>

<p>
  <strong>Data:</strong>
  <%= @acesso.data %>
</p>

<%= link_to 'Edit', edit_acesso_path(@acesso) %> |
<%= link_to 'Back', acessos_path %>