config/routes.rb
Vidashop::Application.routes.draw do
  resources :acessos

  resources :clicks

  devise_for :users
  resources :servers do
    get 'grafico', :on => :collection
    get 'deletar_emails', :on => :collection
    get 'limpar_db', :on => :collection
  end

  resources :emails do
    get 'top', :on => :collection
    get 'exportar_top', :on => :collection
    get 'exportar_acessos', :on => :collection
  end

  root 'servers#index'

  

end

app/models/server.rb
class Server < ActiveRecord::Base
  has_many :email, dependent: :destroy
  has_many :acesso
  has_many :click
  def total_visualizacoes(id)
    server = Server.find(id)
    @total = 0
    server.email.each do |email|
      unless email.visualizacao.nil?
        @total += email.visualizacao
      end
    end
    return @total
  end
  
  def click_dia()
    total_click = click.where(data: Date.today.strftime).count
    return total_click
  end
  
  def click_semana()
    total_click_semana =  click.where("data >= ? AND data < ?", Date.today.at_beginning_of_week.strftime, Date.today.at_end_of_week.strftime).count
    return total_click_semana
  end
  
  def click_mes()
    total_click_mes = click.where('extract(month from data) = ?', Date.today.month).count
    return total_click_mes
  end
 

  
 
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_server, only: [:show, :edit, :update, :destroy]

  # GET /servers
  # GET /servers.json
  def index
    @servers = Server.all
  end
  
  def grafico
    @servers = Server.all
  end
  # GET /servers/1
  # GET /servers/1.json
  def show
  end
  
  def deletar_emails()
    server = Server.find(params[:id])
    server.email.delete_all
    respond_to do |format|
      format.html { redirect_to servers_path, notice: "Emails excluidos do servidor #{server.nome}" } 
    end
  end
  def limpar_db()
    Server.delete_all
    Click.delete_all
    Acesso.delete_all
    Email.delete_all
    respond_to do |format|
      format.html { redirect_to servers_path, notice: "TODOS OS EMAILS FORAM EXCLUIDOS DA BASE" }
    end   
  end
  # GET /servers/new
  def new
    @server = Server.new
  end

  # GET /servers/1/edit
  def edit
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(server_params)

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render action: 'show', status: :created, location: @server }
      else
        format.html { render action: 'new' }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servers/1
  # PATCH/PUT /servers/1.json
  def update
    respond_to do |format|
      if @server.update(server_params)
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server.destroy
    respond_to do |format|
      format.html { redirect_to servers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_server
      @server = Server.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def server_params
      params.require(:server).permit(:nome)
    end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.erb
<%= form_for @server, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :nome, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nome, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit 'Cadastrar', :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                servers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/servers/_grafico.html.erb
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load('visualization', '1.0', {'packages':['corechart']});
      google.setOnLoadCallback(drawChart);
      function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Topping');
        data.addColumn('number', 'Slices');
        data.addRows([
        <% @servers.each do |server| %>
          ['<%= server.nome %>', <%=server.email.count%>],
        <% end %>
        ]);
        // Set chart options
        var options = {'title':'Emails abertos por servidor',
                       'width':600,
                       'height':500};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>
  <div> <h1> Graficos dos servidores </h1> </div>
  <div id="chart_div">
  
  </div>
  

app/views/servers/edit.html.erb
<%- model_class = Server -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/servers/grafico.html.erb
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load('visualization', '1.0', {'packages':['corechart']});
      google.setOnLoadCallback(drawChart);
      function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Topping');
        data.addColumn('number', 'Slices');
        data.addRows([
        <% @servers.each do |server| %>
          ['<%= server.nome %>', <%=server.email.count%>],
        <% end %>
        ]);
        // Set chart options
        var options = {'title':'Emails abertos por servidor',
                       'width':600,
                       'height':500};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>
  <div> <h1> Graficos dos servidores </h1> </div>
  <div id="chart_div">
  
  </div>
  

app/views/servers/index.html.erb
<%- model_class = Server -%>
<div class="page-header">
  <h1>Servidores </h1>
</div>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th style="width:20px"><%= model_class.human_attribute_name(:id) %></th>
      <th style="width:120px"><%= model_class.human_attribute_name(:nome) %></th>
      <th style="width:100px"> Total </th>
      <th style="width:100px"> Hoje </th>
      <th style="width:100px"> Semana </th>
      <th style="width:100px"> Mes </th>
      <th style="width:150px"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @servers.each do |server| %>
      <tr>
        <td><%= link_to server.id, server_path(server) %></td>
        <td><%= server.nome %></td>
        <td><b>Email:</b><%= server.email.count %> <br><b>Acessos:</b> <%= server.acesso.count %><br><b>Clicks:</b> <%= server.click.count %></td>
        <td><b>Email:</b> <%= server.email.where(data: Date.today.strftime).count %><br><b>Acessos:</b> <%= server.acesso.where(data: Date.today.strftime).count %> <br><b>Clicks: </b> <%= server.click_dia() %></td>
        <td><b>Email:</b> <%= server.email.where("data >= ? AND data <= ?", Date.today.at_beginning_of_week.strftime, Date.today.at_end_of_week.strftime).count %> <br><b> Acesso:</b> <%= server.acesso.where("data >= ? AND data <= ?", Date.today.at_beginning_of_week.strftime, Date.today.at_end_of_week.strftime).count %> <br><b>Clicks: </b><%= server.click_semana %></td>
        <td><b>Email</b>: <%= server.email.where('extract(month from data) = ?', Date.today.month).count %> <br> <b>Acesso:</b> <%= server.acesso.where('extract(month from data) = ?', Date.today.month).count %><br><b>Clicks:</b> <%= server.click_mes %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_server_path(server), :class => 'btn btn-mini' %>
          <%= link_to "Deletar Emails", deletar_emails_servers_path(:id => server.id), :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Voce tem certeza?')) }, :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      server_path(server),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Voce tem certeza?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to t('.new', :default => t("helpers.links.new")),
            new_server_path,
            :class => 'btn btn-primary' %>
<%= link_to "Graficos", grafico_servers_path,
            :class => 'btn btn-primary' %>
<%= link_to "Limpar Database", limpar_db_servers_path,
            :class => 'btn btn-danger', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'VOCE ESTA EXCLUINDO TUDO SALDADO O1')) } %>
<br>
<br>
<%= render :partial => 'grafico' %>

app/views/servers/new.html.erb
<%- model_class = Server -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/servers/show.html.erb
<%- model_class = Server -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @server.nome %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              servers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_server_path(@server), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              server_path(@server),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>