config/routes.rb
Vidashop::Application.routes.draw do
  resources :acessos

  resources :clicks

  devise_for :users
  resources :servers do
    get 'grafico', :on => :collection
    get 'deletar_emails', :on => :collection
    get 'limpar_db', :on => :collection
  end

  resources :emails do
    get 'top', :on => :collection
    get 'exportar_top', :on => :collection
    get 'exportar_acessos', :on => :collection
  end

  root 'servers#index'

  

end

app/models/click.rb
class Click < ActiveRecord::Base
  belongs_to :server
  belongs_to :email
end

app/controllers/clicks_controller.rb
class ClicksController < ApplicationController
  before_action :set_click, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /clicks
  # GET /clicks.json
  def index
    @clicks = Click.all
  end

  # GET /clicks/1
  # GET /clicks/1.json
  def show
  end

  # GET /clicks/new
  def new
    @click = Click.new
  end

  # GET /clicks/1/edit
  def edit
  end

  # POST /clicks
  # POST /clicks.json
  def create
    @click = Click.new(click_params)

    respond_to do |format|
      if @click.save
        format.html { redirect_to @click, notice: 'Click was successfully created.' }
        format.json { render action: 'show', status: :created, location: @click }
      else
        format.html { render action: 'new' }
        format.json { render json: @click.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clicks/1
  # PATCH/PUT /clicks/1.json
  def update
    respond_to do |format|
      if @click.update(click_params)
        format.html { redirect_to @click, notice: 'Click was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @click.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clicks/1
  # DELETE /clicks/1.json
  def destroy
    @click.destroy
    respond_to do |format|
      format.html { redirect_to clicks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_click
      @click = Click.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def click_params
      params.require(:click).permit(:ip, :time, :server_id)
    end
end

app/helpers/clicks_helper.rb
module ClicksHelper
end

app/views/clicks/_form.html.erb
<%= form_for(@click) do |f| %>
  <% if @click.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@click.errors.count, "error") %> prohibited this click from being saved:</h2>

      <ul>
      <% @click.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ip %><br>
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.number_field :time %>
  </div>
  <div class="field">
    <%= f.label :server_id %><br>
    <%= f.number_field :server_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clicks/edit.html.erb
<h1>Editing click</h1>

<%= render 'form' %>

<%= link_to 'Show', @click %> |
<%= link_to 'Back', clicks_path %>

app/views/clicks/index.html.erb
<h1>Listing clicks</h1>

<table>
  <thead>
    <tr>
      <th>Ip</th>
      <th>Time</th>
      <th>Server</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clicks.each do |click| %>
      <tr>
        <td><%= click.ip %></td>
        <td><%= click.time %></td>
        <td><%= click.server_id %></td>
        <td><%= link_to 'Show', click %></td>
        <td><%= link_to 'Edit', edit_click_path(click) %></td>
        <td><%= link_to 'Destroy', click, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Click', new_click_path %>

app/views/clicks/new.html.erb
<h1>New click</h1>

<%= render 'form' %>

<%= link_to 'Back', clicks_path %>

app/views/clicks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ip:</strong>
  <%= @click.ip %>
</p>

<p>
  <strong>Time:</strong>
  <%= @click.time %>
</p>

<p>
  <strong>Server:</strong>
  <%= @click.server_id %>
</p>

<%= link_to 'Edit', edit_click_path(@click) %> |
<%= link_to 'Back', clicks_path %>