config/routes.rb
Vidashop::Application.routes.draw do
  resources :acessos

  resources :clicks

  devise_for :users
  resources :servers do
    get 'grafico', :on => :collection
    get 'deletar_emails', :on => :collection
    get 'limpar_db', :on => :collection
  end

  resources :emails do
    get 'top', :on => :collection
    get 'exportar_top', :on => :collection
    get 'exportar_acessos', :on => :collection
  end

  root 'servers#index'

  

end

app/views/layouts/_menu.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Administração</a>
      <div class="nav-collapse">
        <ul class="nav">
          <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Servidores <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Listar", servers_path %></li>
              </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Emails <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Listar", emails_path %></li>
                <li><%= link_to "Mais Visualizados", top_emails_path %></li>
                <li><%= link_to "Exportar Mais Visualizados", exportar_top_emails_path, :target => "_blank" %></li>
                <li><%= link_to "Exportar Todos Emails", emails_path(:format => :xml) %></li>
              </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Configurações <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Excluir Dados", limpar_db_servers_path, :confirm=>'Você deseja excluir todos os dados?' %></li>
              </ul>
          </li>
          <li><%= link_to "Sair", destroy_user_session_path, :method => :delete %></li>
          <%end%>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <br>
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>World Wide Web</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<%= render 'layouts/menu' %>
  <br><br>
  <div class="container">
    <div class="row">
      <div class="span12">
        <%= render 'layouts/messages' %>
      <div>
      <div class="span11"><%= yield %></div>
    </div>
  </div>
  <div class="footer">
   <p align='center'> Sistema  </p>
  </div>
</body>
</html>